spring:
  http:
    encoding:
      charset: UTF-8
      enabled: true

  session:
    store-type: jdbc

  jpa:
    show_sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect

---

spring.profiles: local
spring:
  profiles:
    include: oauth
  h2:
    console:
      enabled: true

---

server:
  port: 8080

spring.profiles: real
spring:
  profiles:
    include: oauth,real-db

---

server:
  port: 8081

spring.profiles: real1
spring:
  profiles:
    include: oauth,real-db

---

server:
  port: 8082

spring.profiles: real2
spring:
  profiles:
    include: oauth,real-db

