spring:
  http:
    encoding:
      charset: UTF-8
      enabled: true

  session:
    store-type: jdbc

  profiles:
    include: oauth,real-db

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect